name: Validating Bicep Syntax

on:
  push:
    branches: [ main ]

jobs:
  validate_bicep:
    name: Check Bicep Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Bicep File
        run: | 
          find . -type f -name "*.bicep" | while read file; do
            echo "🔍 Validating $file..."
            az bicep build --file "$file"
          done

      - name: Validation Passed ✅
        if: success()
        run: echo "The Bicep file syntax is correct and ready for manual deployment."
#v1.0.6